security:
  oauth2:
    resource:
      prefer-token-info: true
      token-info-uri: http://sc-security-uaa/oauth/token
      jwt:
        key-uri: http://sc-security-uaa/oauth/token_key
    client:
      client-id: client
      client-secret: client
      grant-type: client_credentials
      access-token-uri: http://sc-security-uaa/oauth/token
      user-authorization-uri: http://sc-security-uaa/oauth/authorize
spring:
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bookstore?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 827428112mb
  cloud:
    loadbalancer:
      retry:
        enabled: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
sc:
  cloud:
    debug: true
    task:
      core-pool-size: 20
      max-pool-size: 50
      queue-capacity: 200
      keep-alive-seconds: 3000
      thread-name-prefix: sc-task-executor-
    swagger:
      enabled: true
      description: '任务调度'